-- CreateTable
CREATE TABLE "Media" (
    "id" SERIAL NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "author" TEXT NOT NULL,
    "studio" TEXT,
    "genre" TEXT NOT NULL,
    "episodes" INTEGER,
    "chapters" INTEGER,
    "is_completed" BOOLEAN NOT NULL DEFAULT false,
    "release_year" INTEGER,
    "main_character" TEXT,
    "rating" DOUBLE PRECISION,
    "popularity" INTEGER,
    "tags" TEXT[],
    "cover_image_url" TEXT,
    "anime_trailer_url" TEXT,
    "manga_publisher" TEXT,
    "is_anime" BOOLEAN NOT NULL DEFAULT false,
    "is_manga" BOOLEAN NOT NULL DEFAULT false,
    "arcs" TEXT[],
    "side_characters" TEXT[],
    "soundtrack_composer" TEXT,
    "openings" TEXT[],
    "endings" TEXT[],
    "adapted_from" TEXT,
    "original_language" TEXT NOT NULL,
    "dubbed_languages" TEXT[],
    "duration_per_episode" INTEGER,
    "awards" TEXT[],
    "producer" TEXT,
    "director" TEXT,
    "streaming_platforms" TEXT[],
    "manga_volumes" INTEGER,
    "last_update_date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "has_live_action" BOOLEAN NOT NULL DEFAULT false,
    "fanbase_statistics" JSONB,
    "has_funkopop" BOOLEAN NOT NULL DEFAULT false,
    "merchandise" TEXT[],
    "official_website" TEXT,
    "spin_offs" TEXT[],
    "has_video_game" BOOLEAN NOT NULL DEFAULT false,
    "has_novel" BOOLEAN NOT NULL DEFAULT false,
    "collaborations" TEXT[],
    "box_office_revenue" DOUBLE PRECISION,
    "style" TEXT,
    "memorable_quotes" TEXT[],
    "community_events" TEXT[],
    "cosplay_popularity" INTEGER,
    "age_rating" TEXT,
    "critical_reception" DOUBLE PRECISION NOT NULL,
    "release_schedule" TEXT,

    CONSTRAINT "Media_pkey" PRIMARY KEY ("id")
);
